export interface AppColors {
  text: string;
  background: string;
  primary: string;
  tint: string;
  buttonText: string;
  border: string;
  textDim: string;
  isDark: boolean;
  gradient: readonly [string, string, ...string[]];
  tabBarBackground: string;
  tabBarBorder: string;
  tabBarActive: string;
  tabBarInactive: string;
  success: string;
  error: string;
  info: string;
  backgroundSecondary: string;
  textSecondary: string;
  buttonBackgroundSecondary: string;
  buttonTextSecondary: string;
  selectedItemBackground: string;
  overlay: string;
}

export const LightThemeColors: AppColors = {
  background: '#FFFFFF',
  text: '#000',
  textDim: '#2b2b2b',
  border: '#CCCCCC',
  primary: '#2b2b2b',
  gradient: ['#EEEEEE', '#F0f0f0'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFFFFF',
  tabBarBorder: '#DDDDDD',
  tabBarActive: '#2b2b2b',
  tabBarInactive: '#888888',
  isDark: false,
  tint: '#2b2b2b',
  success: '#4CAF50',
  error: '#F44336',
  info: '#2196F3',
  backgroundSecondary: '#F8F8F8',
  textSecondary: '#333333',
  buttonBackgroundSecondary: '#E0E0E0',
  buttonTextSecondary: '#2b2b2b',
  selectedItemBackground: '#E0E0E0',
  overlay: 'rgba(0,0,0,0.3)',
};

export const DarkThemeColors: AppColors = {
  background: '#121212',
  text: '#FFFFFF',
  textDim: '#888',
  border: '#555555',
  primary: '#b0b0b0',
  gradient: ['#1A1A1A', '#171717'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#1A1A1A',
  tabBarBorder: '#333333',
  tabBarActive: '#FFFFFF',
  tabBarInactive: '#888',
  isDark: true,
  tint: '#FFFFFF',
  success: '#66BB6A',
  error: '#EF5350',
  info: '#42A5F5',
  backgroundSecondary: '#1C1C1C',
  textSecondary: '#E0E0E0',
  buttonBackgroundSecondary: '#444444',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#3A3A3A',
  overlay: 'rgba(0,0,0,0.5)',
};

export const OreoThemeColors: AppColors = {
  background: '#2b2b2b',
  text: '#FFFFFF',
  textDim: '#FEFEFE',
  border: '#DDDDDD',
  primary: '#F0F0F0',
  gradient: ['#2b2b2b', '#d9d9d9'],
  buttonText: '#757474',
  tabBarBackground: '#2b2b2b',
  tabBarBorder: '#F0F0F0',
  tabBarActive: '#F0F0F0',
  tabBarInactive: '#FEFEFE',
  isDark: true,
  tint: '#F0F0F0',
  success: '#9CCC65',
  error: '#EF9A9A',
  info: '#90CAF9',
  backgroundSecondary: '#3A3A3A',
  textSecondary: '#EFEFEF',
  buttonBackgroundSecondary: '#666666',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#555555',
  overlay: 'rgba(0,0,0,0.4)',
};

export const YinyangThemeColors: AppColors = {
  background: '#949396',
  text: '#FFFFFF',
  textDim: '#BBBBBB',
  border: '#ADADAD',
  primary: '#FFFFFF',
  gradient: ['#949396', '#1A1A1A'],
  buttonText: '#000000',
  tabBarBackground: '#000000',
  tabBarBorder: '#333333',
  tabBarActive: '#FFFFFF',
  tabBarInactive: '#BBBBBB',
  isDark: true,
  tint: '#FFFFFF',
  success: '#DCE775',
  error: '#FFCDD2',
  info: '#BBDEFB',
  backgroundSecondary: '#78787C',
  textSecondary: '#EFEFEF',
  buttonBackgroundSecondary: '#3B3B3B',
  buttonTextSecondary: '#000000',
  selectedItemBackground: '#A0A0A0',
  overlay: 'rgba(0,0,0,0.5)',
};

export const OceanThemeColors: AppColors = {
  background: '#0288D1',
  text: '#034F84',
  textDim: '#15466A',
  border: '#88C2E3',
  primary: '#0288D1',
  gradient: ['#0288D1', '#26C6DA'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#D0F0FD',
  tabBarBorder: '#88C2E3',
  tabBarActive: '#0288D1',
  tabBarInactive: '#15466A',
  isDark: false,
  tint: '#0288D1',
  success: '#66BB6A',
  error: '#EF5350',
  info: '#42A5F5',
  backgroundSecondary: '#E0F5FF',
  textSecondary: '#034F84',
  buttonBackgroundSecondary: '#E0F5FF',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#B3E5FC',
  overlay: 'rgba(0,0,0,0.3)',
};

export const SunsetThemeColors: AppColors = {
  background: '#F2994A',
  text: '#6B4226',
  textDim: '#945428',
  border: '#c28255',
  primary: '#eb8a34',
  gradient: ['#F2994A', '#F2C94C'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFECD2',
  tabBarBorder: '#D7A75E',
  tabBarActive: '#eb8a34',
  tabBarInactive: '#945428',
  isDark: false,
  tint: '#eb8a34',
  success: '#FFD54F',
  error: '#FF8A65',
  info: '#FFB74D',
  backgroundSecondary: '#FFF4E1',
  textSecondary: '#6B4226',
  buttonBackgroundSecondary: '#FFF4E1',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FFE0B2',
  overlay: 'rgba(0,0,0,0.3)',
};

export const ForestThemeColors: AppColors = {
  background: '#4CAF50',
  text: '#154F1A',
  textDim: '#70631f',
  border: '#2a8031',
  primary: '#1f7025',
  gradient: ['#4CAF50', '#81C784'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#E8F5E9',
  tabBarBorder: '#A5C68E',
  tabBarActive: '#1f7025',
  tabBarInactive: '#70631f',
  isDark: false,
  tint: '#1f7025',
  success: '#81C784',
  error: '#FFAB91',
  info: '#C5E1A5',
  backgroundSecondary: '#E8F5E9',
  textSecondary: '#154F1A',
  buttonBackgroundSecondary: '#E8F5E9',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#C8E6C9',
  overlay: 'rgba(0,0,0,0.3)',
};

export const MidnightThemeColors: AppColors = {
  background: '#2d0961',
  text: '#d7bff5',
  textDim: '#C2A6FF',
  border: '#5D3FD3',
  primary: '#6b15e8',
  gradient: ['#000000', '#2d0961'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#121212',
  tabBarBorder: '#5D3FD3',
  tabBarActive: '#d7bff5',
  tabBarInactive: '#C2A6FF',
  isDark: true,
  tint: '#d7bff5',
  success: '#8E24AA',
  error: '#D32F2F',
  info: '#7E57C2',
  backgroundSecondary: '#1A0436',
  textSecondary: '#E0CCFF',
  buttonBackgroundSecondary: '#1A0436',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#3F1A73',
  overlay: 'rgba(0,0,0,0.6)',
};

export const CandyThemeColors: AppColors = {
  background: '#EC407A',
  text: '#FFFFFF',
  textDim: '#f0daee',
  border: '#F8BBD0',
  primary: '#d91e5e',
  gradient: ['#EC407A', '#AB47BC'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFE6F7',
  tabBarBorder: '#F8BBD0',
  tabBarActive: '#d91e5e',
  tabBarInactive: '#AB47BC',
  isDark: false,
  tint: '#d91e5e',
  success: '#BA68C8',
  error: '#FF8A80',
  info: '#F06292',
  backgroundSecondary: '#FCE4EC',
  textSecondary: '#880E4F',
  buttonBackgroundSecondary: '#f05b8e',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#F8BBD0',
  overlay: 'rgba(0,0,0,0.3)',
};

export const EarthThemeColors: AppColors = {
  background: '#452d25',
  text: '#210e08',
  textDim: '#d6bfb0',
  border: '#B29988',
  primary: '#8f7a72',
  gradient: ['#8a6a5f', '#452d25'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#F4EFEA',
  tabBarBorder: '#B29988',
  tabBarActive: '#452d25',
  tabBarInactive: '#8f7a72',
  isDark: false,
  tint: '#452d25',
  success: '#A1887F',
  error: '#BF360C',
  info: '#D7CCC8',
  backgroundSecondary: '#D7CCC8',
  textSecondary: '#210e08',
  buttonBackgroundSecondary: '#8A6A5F',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#BCAAA4',
  overlay: 'rgba(0,0,0,0.3)',
};

export const DesertThemeColors: AppColors = {
  background: '#f0b859',
  text: '#4E342E',
  textDim: '#4a301b',
  border: '#8a5e3d',
  primary: '#6B8E23',
  gradient: ['#f0b859', '#ba8b09'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF5E1',
  tabBarBorder: '#D7B24E',
  tabBarActive: '#ba8b09',
  tabBarInactive: '#4E342E',
  isDark: false,
  tint: '#ba8b09',
  success: '#A2E12F',
  error: '#D50000',
  info: '#FFEB3B',
  backgroundSecondary: '#FFF9E8',
  textSecondary: '#4E342E',
  buttonBackgroundSecondary: '#ba8b09',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FDD835',
  overlay: 'rgba(0,0,0,0.3)',
};

export const TwilightThemeColors: AppColors = {
  background: '#8E44AD',
  text: '#ECF0F1',
  textDim: '#bfdce3',
  border: '#99bac9',
  primary: '#8E44AD',
  gradient: ['#8E44AD', '#3498DB'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#2C3E50',
  tabBarBorder: '#607D8B',
  tabBarActive: '#3498DB',
  tabBarInactive: '#ECF0F1',
  isDark: true,
  tint: '#3498DB',
  success: '#2ECC71',
  error: '#E74C3C',
  info: '#3498DB',
  backgroundSecondary: '#ac8fc2',
  textSecondary: '#ECF0F1',
  buttonBackgroundSecondary: '#a876cf',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#A066B9',
  overlay: 'rgba(0,0,0,0.5)',
};

export const CoralThemeColors: AppColors = {
  background: '#FF9A8B',
  text: '#f5d0d3',
  textDim: '#2a5166',
  border: '#f2b8ac',
  primary: '#FF6F61',
  gradient: ['#17658f', '#FF9A8B'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF1F0',
  tabBarBorder: '#F19987',
  tabBarActive: '#FF6F61',
  tabBarInactive: '#ff8b94',
  isDark: false,
  tint: '#FF6F61',
  success: '#8BC34A',
  error: '#EF5350',
  info: '#FFCA28',
  backgroundSecondary: '#FFF5F4',
  textSecondary: '#2a5166',
  buttonBackgroundSecondary: '#2776ab',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FFCCBC',
  overlay: 'rgba(0,0,0,0.3)',
};

export const MintThemeColors: AppColors = {
  background: '#00796B',
  text: '#FFFFFF',
  textDim: '#b0f5ee',
  border: '#80CBC4',
  primary: '#00796B',
  gradient: ['#00796B', '#26A69A'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#E0F2F1',
  tabBarBorder: '#80CBC4',
  tabBarActive: '#00796B',
  tabBarInactive: '#004D40',
  isDark: false,
  tint: '#00796B',
  success: '#4CAF50',
  error: '#F44336',
  info: '#00BCD4',
  backgroundSecondary: '#E0F2F1',
  textSecondary: '#004D40',
  buttonBackgroundSecondary: '#175750',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#B2DFDB',
  overlay: 'rgba(0,0,0,0.3)',
};

export const SteelThemeColors: AppColors = {
  background: '#607D8B',
  text: '#37474F',
  textDim: '#425a66',
  border: '#B0BEC5',
  primary: '#607D8B',
  gradient: ['#607D8B', '#90A4AE'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#ECEFF1',
  tabBarBorder: '#B0BEC5',
  tabBarActive: '#37474F',
  tabBarInactive: '#425a66',
  isDark: false,
  tint: '#37474F',
  success: '#8BC34A',
  error: '#FF5722',
  info: '#9E9E9E',
  backgroundSecondary: '#CFD8DC',
  textSecondary: '#263238',
  buttonBackgroundSecondary: '#b8c9d1',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#B0BEC5',
  overlay: 'rgba(0,0,0,0.3)',
};

export const RoyalThemeColors: AppColors = {
  background: '#190c5c',
  text: '#d5d7db',
  textDim: '#8479a8',
  border: '#D1B3FF',
  primary: '#5E35B1',
  gradient: ['#190c5c', '#5007a8'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#F5F0FF',
  tabBarBorder: '#D1B3FF',
  tabBarActive: '#5007a8',
  tabBarInactive: '#8479a8',
  isDark: true,
  tint: '#5007a8',
  success: '#7B1FA2',
  error: '#D32F2F',
  info: '#9C27B0',
  backgroundSecondary: '#2C0A74',
  textSecondary: '#E0DFFF',
  buttonBackgroundSecondary: '#2f085e',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#3F1E8C',
  overlay: 'rgba(0,0,0,0.5)',
};

export const LavenderThemeColors: AppColors = {
  background: '#AB47BC',
  text: '#FFFFFF',
  textDim: '#dbd3e6',
  border: '#CE93D8',
  primary: '#AB47BC',
  gradient: ['#AB47BC', '#BA68C8'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#F3E5F5',
  tabBarBorder: '#CE93D8',
  tabBarActive: '#AB47BC',
  tabBarInactive: '#4A148C',
  isDark: false,
  tint: '#AB47BC',
  success: '#9CCC65',
  error: '#EF5350',
  info: '#CE93D8',
  backgroundSecondary: '#EDE7F6',
  textSecondary: '#4A148C',
  buttonBackgroundSecondary: '#873a94',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#E1BEE7',
  overlay: 'rgba(0,0,0,0.3)',
};

export const PlatinumThemeColors: AppColors = {
  background: '#BDBDBD',
  text: '#212121',
  textDim: '#858383',
  border: '#ACACAC',
  primary: '#9E9E9E',
  gradient: ['#BDBDBD', '#E0E0E0'],
  buttonText: '#000000',
  tabBarBackground: '#F8F8F8',
  tabBarBorder: '#BDBDBD',
  tabBarActive: '#212121',
  tabBarInactive: '#858383',
  isDark: false,
  tint: '#212121',
  success: '#A5D6A7',
  error: '#FFCDD2',
  info: '#B0BEC5',
  backgroundSecondary: '#E0E0E0',
  textSecondary: '#212121',
  buttonBackgroundSecondary: '#c4c4c4',
  buttonTextSecondary: '#000000',
  selectedItemBackground: '#EEEEEE',
  overlay: 'rgba(0,0,0,0.3)',
};

export const BlushThemeColors: AppColors = {
  background: '#EC407A',
  text: '#880E4F',
  textDim: '#D81B60',
  border: '#F8BBD0',
  primary: '#EC407A',
  gradient: ['#EC407A', '#F48FB1'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF5F7',
  tabBarBorder: '#F8BBD0',
  tabBarActive: '#EC407A',
  tabBarInactive: '#880E4F',
  isDark: false,
  tint: '#EC407A',
  success: '#E57373',
  error: '#EF5350',
  info: '#F06292',
  backgroundSecondary: '#FFEBEE',
  textSecondary: '#880E4F',
  buttonBackgroundSecondary: '#FFEBEE',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#F8BBD0',
  overlay: 'rgba(0,0,0,0.3)',
};

export const RosegoldThemeColors: AppColors = {
  background: '#B76E79',
  text: '#bf3b3b',
  textDim: '#875c5c',
  border: '#F7C6C7',
  primary: '#b53f3f',
  gradient: ['#B76E79', '#F7C6C7'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF5F5',
  tabBarBorder: '#F7C6C7',
  tabBarActive: '#b53f3f',
  tabBarInactive: '#875c5c',
  isDark: false,
  tint: '#b53f3f',
  success: '#D4C4C2',
  error: '#C62828',
  info: '#F8BBD0',
  backgroundSecondary: '#FFF0F0',
  textSecondary: '#bf3b3b',
  buttonBackgroundSecondary: '#FFF0F0',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FFCDD2',
  overlay: 'rgba(0,0,0,0.3)',
};

export const SkyThemeColors: AppColors = {
  background: '#03A9F4',
  text: '#01579B',
  textDim: '#0288D1',
  border: '#a2dbf5',
  primary: '#03A9F4',
  gradient: ['#03A9F4', '#81D4FA'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#E0F7FF',
  tabBarBorder: '#81D4FA',
  tabBarActive: '#03A9F4',
  tabBarInactive: '#01579B',
  isDark: false,
  tint: '#03A9F4',
  success: '#4FC3F7',
  error: '#FFEB3B',
  info: '#03A9F4',
  backgroundSecondary: '#F0FAFF',
  textSecondary: '#01579B',
  buttonBackgroundSecondary: '#F0FAFF',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#B3E5FC',
  overlay: 'rgba(0,0,0,0.3)',
};

export const CyberpunkThemeColors: AppColors = {
  background: '#FF00C8',
  text: '#00FFF7',
  textDim: '#9c027a',
  border: '#4E2A84',
  primary: '#FF00C8',
  gradient: ['#FF00C8', '#00FFF7'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#0D0221',
  tabBarBorder: '#4E2A84',
  tabBarActive: '#00FFF7',
  tabBarInactive: '#9c027a',
  isDark: true,
  tint: '#00FFF7',
  success: '#00FF00',
  error: '#FF0000',
  info: '#00FFFF',
  backgroundSecondary: '#1A0436',
  textSecondary: '#00FFF7',
  buttonBackgroundSecondary: '#1A0436',
  buttonTextSecondary: '#00FFF7',
  selectedItemBackground: '#8D009F',
  overlay: 'rgba(0,0,0,0.6)',
};

export const CoffeeThemeColors: AppColors = {
  background: '#795548',
  text: '#332522',
  textDim: '#4a3935',
  border: '#5c4b48',
  primary: '#795548',
  gradient: ['#795548', '#BCAAA4'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#b08d82',
  tabBarBorder: '#6b5249',
  tabBarActive: '#795548',
  tabBarInactive: '#332522',
  isDark: false,
  tint: '#795548',
  success: '#C5E1A5',
  error: '#FF8A65',
  info: '#D7CCC8',
  backgroundSecondary: '#BCAAA4',
  textSecondary: '#332522',
  buttonBackgroundSecondary: '#9c847c',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#D7CCC8',
  overlay: 'rgba(0,0,0,0.3)',
};

export const IceThemeColors: AppColors = {
  background: '#29B6F6',
  text: '#004D80',
  textDim: '#0c6dad',
  border: '#B3E5FC',
  primary: '#29B6F6',
  gradient: ['#29B6F6', '#81D4FA'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#F0FAFF',
  tabBarBorder: '#B3E5FC',
  tabBarActive: '#29B6F6',
  tabBarInactive: '#004D80',
  isDark: false,
  tint: '#29B6F6',
  success: '#81D4FA',
  error: '#FFCDD2',
  info: '#B3E5FC',
  backgroundSecondary: '#E1F5FE',
  textSecondary: '#004D80',
  buttonBackgroundSecondary: '#E1F5FE',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#B3E5FC',
  overlay: 'rgba(0,0,0,0.3)',
};

export const SakuraThemeColors: AppColors = {
  background: '#FF69B4',
  text: '#B03060',
  textDim: '#c24c78',
  border: '#F8C1D2',
  primary: '#FF69B4',
  gradient: ['#FF69B4', '#F8BBD0'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF0F5',
  tabBarBorder: '#F8C1D2',
  tabBarActive: '#FF69B4',
  tabBarInactive: '#B03060',
  isDark: false,
  tint: '#FF69B4',
  success: '#F48FB1',
  error: '#FF8A80',
  info: '#F8BBD0',
  backgroundSecondary: '#FFF8F9',
  textSecondary: '#B03060',
  buttonBackgroundSecondary: '#FFF8F9',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FCE4EC',
  overlay: 'rgba(0,0,0,0.3)',
};

export const FireThemeColors: AppColors = {
  background: '#FF5722',
  text: '#FFFFFF',
  textDim: '#FFFFFF',
  border: '#DFDFDF',
  primary: '#FF5722',
  gradient: ['#FF5722', '#FFC107'],
  buttonText: '#FFFFFF',
  tabBarBackground: '#FFF4E6',
  tabBarBorder: '#FF8A65',
  tabBarActive: '#FF5722',
  tabBarInactive: '#a63c1b',
  isDark: false,
  tint: '#FF5722',
  success: '#FFC107',
  error: '#D32F2F',
  info: '#FF8A65',
  backgroundSecondary: '#302f2f',
  textSecondary: '#E65100',
  buttonBackgroundSecondary: '#a63c1b',
  buttonTextSecondary: '#FFFFFF',
  selectedItemBackground: '#FFE0B2',
  overlay: 'rgba(0,0,0,0.3)',
};

export const Colors = {
  light: LightThemeColors,
  dark: DarkThemeColors,
  oreo: OreoThemeColors,
  yinyang: YinyangThemeColors,
  ocean: OceanThemeColors,
  sunset: SunsetThemeColors,
  forest: ForestThemeColors,
  midnight: MidnightThemeColors,
  candy: CandyThemeColors,
  earth: EarthThemeColors,
  desert: DesertThemeColors,
  twilight: TwilightThemeColors,
  coral: CoralThemeColors,
  mint: MintThemeColors,
  steel: SteelThemeColors,
  royal: RoyalThemeColors,
  lavender: LavenderThemeColors,
  platinum: PlatinumThemeColors,
  blush: BlushThemeColors,
  rosegold: RosegoldThemeColors,
  sky: SkyThemeColors,
  cyberpunk: CyberpunkThemeColors,
  coffee: CoffeeThemeColors,
  ice: IceThemeColors,
  sakura: SakuraThemeColors,
  fire: FireThemeColors,
};